sudo: false

language: node_js

node_js:
  - '4'
  - '5'
  - stable

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

env:
  global:
    - CXX=g++-4.8

script:
  - npm run lint
  - npm test